# Jekyll configuration for Open SDG platform

remote_theme: brockfanning/open-sdg@kazakhstan-feature-set
title: Indicators For The Sustainable Development Goals
baseurl: "/sdg-site-kazstat"
url: ""

# Pages
collections:
  pages:
    output: true
    permalink: /:path/
  posts:
    output: true
    permalink: /news/:year/:month/:day/:title.html
  indicators:
    output: true
  goals:
    output: true

# Tell Jekyll to use the Remote Theme plugin.
plugins:
  - jekyll-remote-theme
  - jekyll-open-sdg-plugins

exclude:
  - vendor
  - scripts
  - remotedata
  - Gemfile
  - Gemfile.lock
  - README
  - README.md
  - LICENSE
  - .sass-cache
